[graph]
exclude-dev = true

[advisories]
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"

[licenses]
allow = [
    "AGPL-3.0",
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unlicense",
    "CC0-1.0",
    "Zlib",
]
exceptions = [{ name = "ring", allow = ["OpenSSL"] }]

[sources]
allow-git = ["https://github.com/esclusehq/agent-core"]
unknown-registry = "deny"
unknown-git = "deny"
