services:
  postgres:
    image: postgres:16-alpine
    container_name: escluse_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: IIXji73OC6DqhpGtiGWg
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: escluse_redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass dU4J99CaxFSQti9jqucZ
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    image: 535237074507.dkr.ecr.ap-southeast-1.amazonaws.com/escluse-backend:latest
    container_name: escluse_backend
    environment:
      DATABASE_URL: postgresql://server:IIXji73OC6DqhpGtiGWg@postgres:5432/backend_db
      REDIS_URL: redis://:dU4J99CaxFSQti9jqucZ@redis:6379
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: "3000"
      GATEWAY_HMAC_SECRET: d3f89ef2c4a1088214e6587f85a394e00cfb72b3711c5d58ec6f22a7259bd637
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  landing:
    image: 535237074507.dkr.ecr.ap-southeast-1.amazonaws.com/escluse-landing:latest
    container_name: escluse_landing
    ports:
      - "8081:80"
    networks:
      - app-network

  frontend:
    image: 535237074507.dkr.ecr.ap-southeast-1.amazonaws.com/escluse-frontend:latest
    container_name: escluse_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  worker:
    image: 535237074507.dkr.ecr.ap-southeast-1.amazonaws.com/escluse-worker:latest
    container_name: escluse_worker
    environment:
      DATABASE_URL: postgresql://server:IIXji73OC6DqhpGtiGWg@postgres:5432/backend_db
      REDIS_URL: redis://:dU4J99CaxFSQti9jqucZ@redis:6379
      JWT_SECRET: dev-secret-key-min-32-chars-long
      APP_URL: https://esluce.com
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  docs:
    image: 535237074507.dkr.ecr.ap-southeast-1.amazonaws.com/escluse-docs:latest
    container_name: escluse_docs
    ports:
      - "8082:80"
    networks:
      - app-network

  caddy:
    image: caddy:2
    container_name: escluse_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  redis_data:
