use crate::mermaid_generator;
use crate::types::{DomainSection, TableInfo};

pub fn build_document(domains: &[DomainSection]) -> String {
    let mut doc = String::new();

    doc.push_str("# Escluse — Database Schema\n\n");
    doc.push_str(
        "Database schema reference for the Esluce platform. This document describes all PostgreSQL tables, columns, relationships, constraints, and indexes organized by business domain. Generated from live database introspection.\n\n",
    );
    doc.push_str("![PostgreSQL](https://img.shields.io/badge/postgresql-16-336791)\n");
    doc.push_str("![Rust](https://img.shields.io/badge/generator-rust-orange)\n\n");
    doc.push_str("---\n\n");

    doc.push_str("## Table of Contents\n\n");
    for domain in domains {
        let anchor = domain.name.to_lowercase().replace(' ', "-").replace('/', "-");
        doc.push_str(&format!("- [{} Tables](#{}-tables)\n", domain.name, anchor));
    }
    doc.push_str("- [Migration History](#migration-history)\n\n");
    doc.push_str("---\n\n");

    doc.push_str(
        "> **Note:** This document is auto-generated by `tools/db-schema-gen/`. Regenerate when the schema changes by running:\n\
         > ```bash\n\
         > cargo run --manifest-path tools/db-schema-gen/Cargo.toml -- --db-url \"$DATABASE_URL\"\n\
         > ```\n\n",
    );

    for domain in domains {
        doc.push_str(&build_domain_section(domain));
    }

    doc.push_str("## Migration History\n\n");
    doc.push_str(
        "For the full schema evolution timeline showing each change by date, see `api/migrations/` in the repository. This file contains 69 timestamped SQL migration files.\n",
    );

    doc
}

pub fn build_domain_section(domain: &DomainSection) -> String {
    let mut section = String::new();

    let anchor = domain.name.to_lowercase().replace(' ', "-").replace('/', "-");
    section.push_str(&format!("## {} Tables\n\n", domain.name));
    section.push_str(&domain.description);
    section.push_str("\n\n");

    for cluster in &domain.clusters {
        let diagram = mermaid_generator::generate_er_diagram(cluster);
        let validated = mermaid_generator::validate_er_diagram(&diagram);
        section.push_str(&validated);
        section.push('\n');
    }

    for table in &domain.tables {
        section.push_str(&build_table_section(table));
    }

    if !domain.query_patterns.is_empty() {
        section.push_str("### Common Query Patterns\n\n");
        for pattern in &domain.query_patterns {
            section.push_str(&format!("```sql\n{}\n```\n\n", pattern));
        }
    }

    if !domain.design_rationale.is_empty() {
        section.push_str("### Design Rationale\n\n");
        for rationale in &domain.design_rationale {
            section.push_str(&format!("- {}\n", rationale));
        }
        section.push('\n');
    }

    section
}

pub fn build_table_section(table: &TableInfo) -> String {
    let mut section = String::new();
    section.push_str(&format!("### `{}`\n\n", table.table_name));

    if let Some(ref comment) = table.table_comment {
        section.push_str(comment);
        section.push_str("\n\n");
    }

    section.push_str("| Column | Type | Constraints | Description |\n");
    section.push_str("|--------|------|-------------|-------------|\n");

    for col in &table.columns {
        let mut constraints = Vec::new();
        if col.is_pk {
            constraints.push("PK".to_string());
        }
        if col.is_fk {
            let fk_desc = table
                .foreign_keys
                .iter()
                .find(|fk| fk.column_name == col.name)
                .map(|fk| format!("FK → {}.{}", fk.foreign_table_name, fk.foreign_column_name))
                .unwrap_or_else(|| "FK".to_string());
            constraints.push(fk_desc);
        }
        if col.is_nullable {
            constraints.push("NULLABLE".to_string());
        } else {
            constraints.push("NOT NULL".to_string());
        }
        if let Some(ref default) = col.default {
            if !default.is_empty() {
                constraints.push(format!("DEFAULT {}", default));
            }
        }

        let constraints_str = constraints.join(", ");
        let description = col
            .description
            .clone()
            .or_else(|| auto_describe_column(&col.name));

        section.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            col.name,
            col.data_type,
            constraints_str,
            description.as_deref().unwrap_or(""),
        ));
    }

    section.push('\n');
    section
}

fn auto_describe_column(name: &str) -> Option<String> {
    if name.ends_with("_id") {
        let resource = name.trim_end_matches("_id");
        return Some(format!("References the {} resource", resource));
    }
    match name {
        "created_at" => Some("Record creation timestamp".to_string()),
        "updated_at" => Some("Last modification timestamp".to_string()),
        "deleted_at" => Some("Soft delete timestamp".to_string()),
        _ => None,
    }
}
